name: telemusic_v2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.3+22

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  shared_preferences:
  intl:
  http:
  permission_handler:
  equatable:
  # get_it:
  google_fonts:
  get:
  flutter_svg:
  html_to_flutter: ^0.2.3-dev.8
  we_slide: ^2.4.0
  cached_network_image: 
  just_audio:
  audio_service:  
  path_provider:
  dio: ^5.8.0+1
  flutter_widget_from_html_core:
  flutter_native_splash:
  flutter_launcher_icons:
  google_mobile_ads:
  flutter_stripe: ^11.4.0
  in_app_purchase: ^3.2.1
  flutter_paypal_payment: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: "#fee601"  # Background color
  image: assets/images/telemusic_logo.jpg  # Path to splash image
  android: true
  ios: true


flutter_launcher_icons:
  android: true
  ios: true
  color: "#fee601"  # Background color
  image_path: "assets/images/telemusic_logo.jpg"  
  adaptive_icon_background: "#fee601"  # (Optional) Background color for Android adaptive icons
  # adaptive_icon_foreground: "assets/icon_foreground.png"  # (Optional) Foreground icon for Android adaptive icons


